# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "keks@keks.net",
  "avatarPath": "keks.png",
  "name": "Keks",
  "password": "123456",
  "type": "Regular"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks111@keks.net",
  "password": "123456"
}
