# Комментарии
## Все комментарии для предложения

GET http://localhost:5000/comments/offerId HTTP/1.1
Content-Type: application/json

###

# Комментарии
## Создание комментария

POST http://localhost:5000/comments/offerId HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NAa2Vrcy5uZXQiLCJuYW1lIjoiS2VrcyIsImlkIjoiNjcxM2JmZGRiZTdiMTZjNDg5NTE2MTkwIiwiaWF0IjoxNzMwNzE0NjEzLCJleHAiOjE3MzA4ODc0MTN9.7Om33pMEEId1vu9lyP8TB4b1Ou8-XVjsDOXAAbhONwY

{
  "text": "Sample comment",
  "rating": 4
}
